import { COLORS } from './commonStyles';

export const initialExpenseCategories = [
  { name: 'add', color: '' },
  { name: 'food', color: COLORS.RED[100] },
  { name: 'bills', color: COLORS.VIOLET[100] },
  { name: 'shopping', color: COLORS.YELLOW[100] },
  { name: 'subscription', color: '#fc803d' },
  { name: 'transportation', color: COLORS.BLUE[100] },
];
export const initialIncomeCategories = [
  { name: 'add', color: '' },
  { name: 'salary', color: COLORS.GREEN[100] },
  { name: 'passive income', color: '#f531d7' },
];

export const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
export const nameRegex = /^[a-zA-Z ]*$/;
export const passRegex =
  /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z\d\s])[A-Za-z\d\W\s]{8,}$/;

export const STRINGS = {
  ResetPassword: 'Reset Password',
  ClearRepeatTransaction:
    'Clearing Repeat Transaction Frequency \nAre you sure you want to clear the repeat transaction frequency?',
  ToManyRequestError: 'Too many requests. Please try again after sometime.',
  PopupClosedByUser: 'Authentication process canceled. Please try again.',
  Categories: 'Categories',
  Filters: 'Filters',
  Percentage: 'Percentage',
  Limit: 'Limit',
  Spent: 'Spent',
  Left: 'Left',
  Overview: 'Overview',
  TermsError: 'Please accept the terms and conditions',
  EmailSent: 'Password Reset Email Sent',
  Dashboard: 'Dashboard',
  ClearAll: 'Clear All',
  Recent: 'Recent',
  InvalidEmail: 'Invalid Email Address',
  Ok: 'Ok',
  Resend: 'Resend',
  AccountBalance: 'Account Balance',
  FileError: 'File should be less than 10 Mb',
  PleaseFillBothFields: 'Please fill both the fields.',
  PleaseSelectOption: 'Please select an option',
  Cancel: 'Cancel',
  NoDataToExport: 'There is no data to be exported',
  Verify: 'Verify',
  LOGIN: 'Login',
  SIGNUP: 'Sign Up',
  EmailOnWay: 'Your email is on the way',
  ResetEmailSent:
    'Please check your email to reset your password. The link will expire soon, so be sure to use it promptly.',
  CheckYourEmail: 'Check your email',
  InstructionResetPass:
    'and follow the instructions to reset your password. This link will expire soon, please ensure you access it promptly.',
  BackToLogin: 'Back to Login',
  DontWorry: "Don't worry.",
  EnterEmailForReset:
    "Enter your email and we'll send you a link to reset your password.",
  Continue: 'Continue',
  Email: 'Email',
  Name: 'Name',
  Password: 'Password',
  ConfrimPassword: 'Confirm Password',
  BySigningUp: 'By signing up, you agree to the',
  Terms: 'Terms of Service and Privacy Policy',
  OrWith: 'Or with',
  Or: 'Or',
  SignupWithGoogle: 'Sign Up with Google',
  AlreadyHaveAccount: 'Already have an Account?',
  EmailVerificationSent: 'A verification email has been sent to your account.',
  CategoryName: 'Category Name',
  Add: 'Add',
  Home: 'Home',
  Transaction: 'Transaction',
  Budget: 'Budget',
  Profile: 'Profile',
  Removebudget: 'Remove this budget?',
  SureRemoveBudgetNo: 'Are you sure you want to remove this budget?',
  No: 'No',
  Yes: 'Yes',
  BudgetDeletedSuccesfully: 'Budget Deleted Successfully',
  BudgetCreatedSuccesfully: 'Budget Created Successfully',
  BudgetUpdatedSuccesfully: 'Budget Updated Successfully',
  RemovethisTransaction: 'Remove this Transaction?',
  sureRemoveTransaction: 'Are you sure you want to remove this transaction?',
  TransactionDeletedSuccesfully: 'Transaction Deleted Successfully',
  Camera: 'Camera',
  Gallery: 'Gallery',
  Image: 'Image',
  Document: 'Document',
  FilterTransaction: 'Filter Transaction',
  Reset: 'Reset',
  FilterBy: 'Filter By',
  Income: 'Income',
  Expense: 'Expense',
  Transfer: 'Transfer',
  Highest: 'Highest',
  Lowest: 'Lowest',
  Newest: 'Newest',
  Oldest: 'Oldest',
  Category: 'Category',
  ChooseCategory: 'Choose Category',
  Apply: 'Apply',
  SortBy: 'Sort By',
  Month: 'Month',
  Day: 'Day',
  Date: 'Date',
  Next: 'Next',
  PleaseFillAnAmount: 'Please fill an amount',
  PleaseFillValidAmount: 'Please fill a valid amount',
  PleaseSelectACategory: 'Please select a category',
  Description: 'Description',
  Wallet: 'Wallet',
  PleaseSelectAWallet: 'Please select a wallet',
  AddAttachement: 'Add Attachment',
  Repeat: 'Repeat',
  RepeatTransaction: 'Repeat Transaction',
  Frequency: 'Frequency',
  EndAfter: 'End After',
  NoBudgetForThisMonth: "You don't have a budget for this month.",
  NoBudget: "You don't have a budget.",
  CreateBudgetForThisMonth: "Let's make one so you are in control.",
  LimitExceeded: "You've exceeded the limit!",
  CreateABudget: 'Create a Budget',
  CreateBudget: 'Create Budget',
  HowMuch: 'How much?',
  SliderError: 'Value cannot be zero. Please adjust the slider',
  HowMuchDoSpent: 'How much do you want to spend?',
  RecieveAlert: 'Receive Alert',
  RecieveAlertWhen: 'Receive alert when it reaches',
  SomePoint: 'some point.',
  Remaining: 'Remaining',
  Edit: 'Edit',
  Whendaterange: 'When date range?',
  WhatFormat: 'What format do you want to export?',
  DetailBudget: 'Detail Budget',
  Export: 'Export',
  NoData: 'No Data',
  NotEnoughData: 'Not enough data',
  Today: 'Today',
  Week: 'Week',
  Year: 'Year',
  LoginGoogle: 'Log in with Google',
  ForgotPasswordTitle: 'Forgot Password',
  ForgotPassword: 'Forgot Password ?',
  DontHaveAccount: "Don't have an account yet?",
  Notifications: 'Notifications',
  NoNotification: 'There is no notification for now.',
  BudgetExceed: 'budget has exceeded the limit',
  MarkAllRead: 'Mark all Read',
  RemoveAll: 'Remove all',
  SetupPin: "Let's setup your PIN",
  RetypePin: 'Retype your PIN',
  EnterPin: 'Enter Your Pin',
  Username: 'Username',
  Account: 'Account',
  Settings: 'Settings',
  ExportData: 'Export Data',
  Logout: 'Logout',
  Currency: 'Currency',
  Theme: 'Theme',
  DetailTransaction: 'Detail Transaction',
  FinancialReport: 'Financial Report',
  ThisMonth: 'This Month',
  YouSpend: 'You Spend',
  YouEarned: 'You Earned',
  BudgetLimitExceed: ' Budget exceeds the limit',
  Quote: '“Financial freedom is freedom from fear.”',
  QuoteAuthor: '-Robert Kiyosaki',
  BiggestSpending: 'and your biggest spending is from',
  BiggestIncome: 'your biggest Income is from',
  SeeFullDetail: 'See the full detail',
  Light: 'Light',
  Dark: 'Dark',
  UseDeviceTheme: 'Use Device Theme',
  Type: 'Type',
  Attachement: 'Attachment',
  SampleDesc:
    ' Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
  ViewDocument: 'View Document',
  SeeFinancialReport: 'See your financial report',
  SpendFrequency: 'Spend Frequency',
  RecentTransaction: 'Recent Transaction',
  SeeAll: 'See All',
  From: 'From',
  To: 'To',
  WhatExport: 'What data do you want to export?',
  SureLogout: 'Are you sure you want to log out?',
  NoInternetAccess: 'No Internet Access',
  CheckInternet: 'Please check your internet connection',
  PasswordDoNotMatch: 'Password do not match',
  ConfirmPasswordCannotBeEmpty: 'Confirm Password cannot be Empty',
  PasswordNotValid:
    'Password must contain atleast 1 Uppercase, 1 Lowercase, 1 Numeric and 1 Symbol Character',
  PasswordCannotBeEmpty: 'Password cannot be Empty',
  EmailIsNotValid: 'Email is not Valid',
  EmailCannotBeEmpty: 'Email cannot be Empty',
  NameIsNotValid: 'Name is not Valid',
  NameCannotBeEmpty: 'Name cannot be Empty',
  NoRecentTransactions: 'No Recent Transactions',
  NoTransactions: 'No Transactions',
  ResetPin: 'Reset Pin',
  CategoryCannotBeEmpty: 'Category cannot be empty',
  AlreadyAdded: ' is already added',
  Selected: 'Selected',
  PinMust4digits: 'Pin must be of 4 digits',
  PinDontMatch: "Pin doesn't match",
  IncorrectPin: 'Incorrect Pin',
  NoTransactionsMonth: 'No Transactions for this Month',
  PleaseVerifyEmail: 'Please verify your email',
  VerifyEmailSent:
    'A verification email has already been sent to your registered email address, so verify your email before login.',
  AreYouSure: 'Are you sure ?',
  AreYouSureDelete: 'Are you sure you want to delete all the notifications.',
  DiscardChanges: 'Discard changes?',
  UnsavedChanges:
    'You have unsaved changes. Are you sure you want to discard them and leave the screen?',
  EmailNotRegistered: 'This email is not registered',
  LeaveWithoutSettingPin:
    'Are you sure you want to leave without setting up your pin?',
  EmailAdressAlreadyUsed:
    'The email address is already in use by another account.',
  CredentialMalformed: 'Incorrect email or password. Please try again.',
  NetworkError:
    'A network error (such as timeout, interrupted connection or unreachable host) has occurred.',
  UnknownError: 'An unknown error occurred. Please try again later.',
  PasswordResetSucessful: 'Password Reset Sucessful',
};
export const OnboardData = [
  {
    icon: '../../assets/images/onboarding1.png',
    text1: 'Gain total control of your money',
    text2: 'Become your own money manager and make every cent count',
  },
  {
    icon: '../../assets/images/onboarding2.png',
    text1: 'Know where your money goes',
    text2:
      'Track your transactions easily with categories and financial report ',
  },
  {
    icon: '../../assets/images/onboarding3.png',
    text1: 'Planning ahead',
    text2: 'Setup your budget for each category so you are in control',
  },
];

export const monthData = [
  { label: 'January', value: 1 },
  { label: 'February', value: 2 },
  { label: 'March', value: 3 },
  { label: 'April', value: 4 },
  { label: 'May', value: 5 },
  { label: 'June', value: 6 },
  { label: 'July', value: 7 },
  { label: 'August', value: 8 },
  { label: 'September', value: 9 },
  { label: 'October', value: 10 },
  { label: 'November', value: 11 },
  { label: 'December', value: 12 },
];

export const weekData = [
  { label: 'Sunday', value: 0 },
  { label: 'Monday', value: 1 },
  { label: 'Tuesday', value: 2 },
  { label: 'Wednesday', value: 3 },
  { label: 'Thursday', value: 4 },
  { label: 'Friday', value: 5 },
  { label: 'Saturday', value: 6 },
];

export const FreqDropdownData = [
  { label: 'Yearly', value: 'yearly' },
  { label: 'Monthly', value: 'monthly' },
  { label: 'Weekly', value: 'weekly' },
  { label: 'Daily', value: 'daily' },
];
export const EndDropdownData = [
  { label: 'Never', value: 'never' },
  { label: 'Date', value: 'date' },
];

export const currencies: {
  [key: string]: { name: string; symbol: string; code: string };
} = {
  USD: { name: 'United States Dollar', symbol: '$', code: 'USD' },
  EUR: { name: 'Euro', symbol: '€', code: 'EUR' },
  GBP: { name: 'British Pound Sterling', symbol: '£', code: 'GBP' },
  JPY: { name: 'Japanese Yen', symbol: '¥', code: 'JPY' },
  CHF: { name: 'Swiss Franc', symbol: 'CHF', code: 'CHF' },
  CAD: { name: 'Canadian Dollar', symbol: 'C$', code: 'CAD' },
  AUD: { name: 'Australian Dollar', symbol: 'A$', code: 'AUD' },
  NZD: { name: 'New Zealand Dollar', symbol: 'NZ$', code: 'NZD' },
  CNY: { name: 'Chinese Yuan', symbol: '¥', code: 'CNY' },
  INR: { name: 'Indian Rupee', symbol: '₹', code: 'INR' },
  RUB: { name: 'Russian Ruble', symbol: '₽', code: 'RUB' },
  BRL: { name: 'Brazilian Real', symbol: 'R$', code: 'BRL' },
  ZAR: { name: 'South African Rand', symbol: 'R', code: 'ZAR' },
  MXN: { name: 'Mexican Peso', symbol: 'Mex$', code: 'MXN' },
  SGD: { name: 'Singapore Dollar', symbol: 'S$', code: 'SGD' },
  HKD: { name: 'Hong Kong Dollar', symbol: 'HK$', code: 'HKD' },
  SEK: { name: 'Swedish Krona', symbol: 'kr', code: 'SEK' },
  NOK: { name: 'Norwegian Krone', symbol: 'kr', code: 'NOK' },
  DKK: { name: 'Danish Krone', symbol: 'kr', code: 'DKK' },
  KRW: { name: 'South Korean Won', symbol: '₩', code: 'KRW' },
};
